### ISSUE TITLE
Translation problems (es.ts)

### ISSUE THREAD

**Issue by NinjaSasser00** [nulloy/nulloy#104]
The file named <strong>es.ts</strong> have some translation problems
The problems are:

1)line 132:
     BAD: <pre>`<translation>Siempre En Cima</translation>`</pre>
     GOOD: <pre>`<translation>Siempre Encima</translation>`</pre>

2) line137: 
     BAD: <pre>`<translation>Patalla Completa</translation>`</pre>
     GOOD: <pre>`<translation>Pantalla Completa</translation>`</pre>

3)line642:
     BAD: <pre>`<translation>Elemto en Lista de Reproduccion  :</translation>`</pre>
     GOOD: <pre>`<translation>Elemento en Lista de Reproducción  :</translation>`</pre>

**Comment by noscript** [comment]
Thank you! The typos will be corrected.
