### ISSUE TITLE
How do you remove control buttons (pause/ff) 

### ISSUE THREAD

**Issue by radinsky** [nulloy/nulloy#107]
How do you remove control buttons (pause/ff) ?
![image](https://cloud.githubusercontent.com/assets/4540268/13506205/b003ee14-e185-11e5-83e5-08e72931cefd.png)

**Comment by noscript** [comment]
Inside `slim.nzs` there is `script.js` file. Open it and add to the end of `Main()` function:
```
Ui.playButton.hide();
Ui.prevButton.hide();
Ui.nextButton.hide();
```

**Comment by radinsky** [comment]
Is that the only option to change the source (I have no way to compile it on my macbook at home).
Any chance you can add like modified skin "Slim Minimal" or something?
Thanks!

**Comment by noscript** [comment]
No need to build from source. Right click on `Nulloy.app` and select "Show Package Contents". Navigate to `Contents/MacOS/skins` and you will find `slim.nzs` there. It's a normal zip archive. You can extract it into `skins/slim` directory and remove the original `slim.nzs` file. Then edit `script.js` and restart the player.

I plan to add a style editor on the future versions #108.

**Comment by radinsky** [comment]
Excellent, thanks

**Comment by radinsky** [comment]
How do you compress it back to be openable in the player?
Compressed back on osx and renamed to nzs, but it became unreadable:
![image](https://cloud.githubusercontent.com/assets/4540268/13511625/981da812-e19e-11e5-9fcb-bad1a2065e9e.png)

**Comment by radinsky** [comment]
even after removing the lines I added, still not readable.

**Comment by noscript** [comment]
You don't need to repack it. The skin will be recognized as a directory. You should have the following structure (some parts omitted):

```
Nulloy.app
└── Contents
    └── MacOS
        └── plugins
        └── skins
            ├── metro.nzs
            ├── silver.nzs
            └── slim
                ├── form.ui
                ├── id.txt
                ├── script.js
                └── *.png
```

**Comment by radinsky** [comment]
Yes, everything working, thanks

**Comment by vitaly-zdanevich** [comment]
Maybe add such option to preferences?
