### ISSUE TITLE
Flac crash on 0.81 & 0.82 ver.

### ISSUE THREAD

**Issue by fluoelf** [nulloy/nulloy#109]
Hello,
Using this program for a couple of years and I love its simplicity and the very useful waveform, thanks for that. But the latest 2 versions crash as soon as I add a flac file. It doesn't happen with 0.8, which I'm currently using. Good luck :)

**Comment by noscript** [comment]
Hello. Are you using Windows?

**Comment by fluoelf** [comment]
Yes, last update for windows 8

**Comment by noscript** [comment]
GStreamer broke FLAC somehow in recent versions. Please try to take libFLAC-8.dll from 0.8 and put it to 0.8.2. The dll is under `Nulloy\Plugins\GStreamer` directory.

**Comment by fluoelf** [comment]
Hey man, that is great! Now ver. 0.82 is working with flac :D I really appreciate, it was very helpful from your side. Keep up the good work :)
