### ISSUE TITLE
Unicode not displaying properly

### ISSUE THREAD

**Issue by s0nspark** [nulloy/nulloy#118]
I am seeing that at least some unicode tags are not displaying properly...

They do display correctly as filenames... in this screenshot I added the same file twice to illustrate.

![image](https://cloud.githubusercontent.com/assets/7814/23754191/15861166-04aa-11e7-8e5e-181838664d51.png)

I am using TagLib as the TagReader and I checked this file using the Ruby TagLib gem and TagLib does seem to read the tag correctly:

```Ruby
require 'taglib'

TagLib::MPEG::File.open("01 - Traskdod.mp3") {|f| puts f.id3v2_tag.title } #=> Träskdöd
```

**Comment by noscript** [comment]
Can you please upload the file somewhere?

**Comment by s0nspark** [comment]
Sure - here you go :)

https://we.tl/q7JmgLD1vW

**Comment by noscript** [comment]
In addition to the fix, "UTF-8" tags encoding should be selected in Preferences.

**Comment by s0nspark** [comment]
Awesome - thanks so much!
