### ISSUE TITLE
Qt5 migration

### ISSUE THREAD

**Issue by noscript** [nulloy/nulloy#122]

**Comment by plater** [comment]
openSUSE is dropping the package due to qt4 dependency and I can't find it in Debian and Ubuntu so R.I.P

**Comment by noscript** [comment]
It's almost done, still fighting occasional crashes on macOS and Windows.

**Comment by plater** [comment]
I don't see a qt5 branch in git, haven't looked but will master work with qt5 on linux?

**Comment by plater** [comment]
Master hasn't been ported to qt5 yet:
playlistWidget.cpp: In member function 'virtual void NPlaylistWidget::mouseMoveEvent(QMouseEvent*)':
playlistWidget.cpp:727:32: error: invalid use of incomplete type 'class QDrag'
     m_itemDrag = new QDrag(this);
                                ^
In file included from /usr/include/qt5/QtWidgets/qlistview.h:44:0,
                 from /usr/include/qt5/QtWidgets/qlistwidget.h:44,
                 from /usr/include/qt5/QtWidgets/QListWidget:1,
                 from playlistWidget.h:20,
                 from playlistWidget.cpp:16:
/usr/include/qt5/QtWidgets/qabstractitemview.h:57:7: note: forward declaration of 'class QDrag'
 class QDrag;
       ^~~~~
Looking at https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5 it seems easily fixable.

**Comment by noscript** [comment]
I have a private branch where I do the porting.

**Comment by plater** [comment]
Make the branch available, I tried master with a small patch for configure and it seems to only need a few include changes.

**Comment by noscript** [comment]
Published the branch. README is updated only for Debian build instructions, still can be used to collect dependencies list for OpenSUSE

https://github.com/nulloy/nulloy/tree/qt5

**Comment by plater** [comment]
Build fails on:
In file included from playbackEngineVlc.cpp:16:0:
playbackEngineVlc.h:75:21: error: ‘N::MessageBox’ has not been declared
     void message(N::MessageBox::Icon icon, const QString &title, const QString &msg);
                     ^~~~~~~~~~
playbackEngineVlc.h:75:38: error: expected ‘,’ or ‘...’ before ‘icon’
     void message(N::MessageBox::Icon icon, const QString &title, const QString &msg);
                                      ^~~~
playbackEngineVlc.cpp: In member function ‘virtual void NPlaybackEngineVlc::setMedia(const QString&)’:
playbackEngineVlc.cpp:91:25: error: ‘N::MessageBox’ has not been declared
         emit message(N::MessageBox::Warning, file, "No such file or directory");
                         ^~~~~~~~~~

**Comment by noscript** [comment]
VLC plugin hasn't been updated, will try to fix this.

**Comment by plater** [comment]
BTW this patch was used on the qt4 version, I've rebased it for the qt5 branch:

[fix-library-directory.patch.txt](https://github.com/nulloy/nulloy/files/3137210/fix-library-directory.patch.txt)

**Comment by plater** [comment]
It builds with rpmbuild without the --vlc flag, I've included --gstreamer-tagreader.
I need to patch "/usr/nulloy/plugins/" to become /usr/lib64/nulloy/plugins and find the qt package that's missing in the obs build. Then we're good to go.
This is where the obs build chokes:
[    5s] + make V=1 -j4
[    5s] cd src/widgetCollection/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /home/abuild/rpmbuild/BUILD/nulloy-d15e0f3aee22ef1cdd84729cf75f505adcc0ffda/src/widgetCollection/widgetCollection.pro ) && make -f Makefile 
[    5s] Project ERROR: Unknown module(s) in QT: designer
[    5s] make: *** [Makefile:50: sub-src-widgetCollection-make_first-ordered] Error 3
[    5s] error: Bad exit status from /var/tmp/rpm-tmp.EMvdYl (%build)

**Comment by plater** [comment]
Got the obs build working, needed libqt5-qttools-devel and two private header devel poackages.
I've put it in multimedia:apps.

**Comment by plater** [comment]
Never having used nulloy before, the qt5 version works fine drag and drop and all. The Native and Silver skins don't have a menu icon but have a much bigger waveform display, I like the way clicking on the waveform moves the song to that position.
This is tested with Qt 5.9.4 and Qt 5.12.3

**Comment by noscript** [comment]
VLC plugin should be build again via fc10f2d.

**Comment by plater** [comment]
Added two patches to bring it up to date. Both phonon and vlc plugins build.

**Comment by noscript** [comment]
Applied the library dir path in d3534e7 with some corrections. Omitted patching the names for `qmake` and `lrelease` as it is possible to set them through environment variables:
```sh
QMAKE=qmake-qt5 LRELEASE=lrelease-qt5 ./configure
```

**Comment by plater** [comment]
You missed this:
"-            if command -v realpath &> /dev/null && -d $(dirname "$1"); then
"+            if command -v realpath &> /dev/null && [ -d $(dirname "$1") ]; then
Which prevents this:
./configure --no-update-check --prefix /data/packages/BUILDROOT/nulloy-0.8.2.pre61qt5-0.x86_64/usr --vlc --phonon --libdir lib64 --gstreamer-tagreader
./configure: line 49: -d: command not found

**Comment by plater** [comment]
Other remaining issue is:
usr/bin/qmake-qt5 -install qinstall -exe ../../../plugins/libplugin_gstreamer.so /home/abuild/rpmbuild/BUILDROOT/nulloy-0.8.2.pre61qt5-0.x86_64/usr/nulloy/plugins/libplugin_gstreamer.so
The plugins are installed under /usr/nulloy/plugins/ and I physically move them to /usr/l$LIBDIR/nulloy/plugins/ using mv. They function correctly, I can't seem to find where this happens, I haven't much qmake experience.

**Comment by noscript** [comment]
```
./configure: line 49: -d: command not found
```

This was fixed some time later.

Is there still a problem with plugins installation?
