### ISSUE TITLE
Display mono/stereo bug

### ISSUE THREAD

**Issue by davesegway** [nulloy/nulloy#126]
There is an option in the Track Information settings to use %c to display Channels (I'm assuming it should display "1" or "2" for mono/stereo). But it does not work because there is another attribute that uses %c.  In the help panel is says: 

**%c** - Comment
**%c** - Number of channels

When I use "%c", it defaults to "Comment" so instead of displaying the channels, it says "< Empty Comment >".

On a side note, on this subject, I think the default on the top left should be kbps/kHz/channels (or mono/stereo)

Thanks!

![percent c issue](https://user-images.githubusercontent.com/29584374/27357387-e24afb04-55c6-11e7-8053-f6cdf080ced1.png)

**Comment by noscript** [comment]
This has been fixed in fd82451. Sorry I'm delaying with the release, but the fix will be included.
