### ISSUE TITLE
Clicking beyond half point stops playback

### ISSUE THREAD

**Issue by ilunvik** [nulloy/nulloy#130]
When I click towards the end of nulloys screen to skip to another place in the sound file, playback stops and it jumps to the start of the file.

When I have played past the point i clicked, I can click a bit further, and eventually I can click anywhere.

Is it a caching issue?

I run Nulloy 0.8.2. alpha on Windows 10 Home.

**Comment by noscript** [comment]
I believe that was the issue with gapless playback. When the position is around the end of a track, GStreamer  requests the next track. Clicking during that transition phase would abruptly just to the next track.

Please try 0.9.7 or newer, the should be fixed.
