### ISSUE TITLE
no sound on mac

### ISSUE THREAD

**Issue by tzzsmk** [nulloy/nulloy#134]
Hello everyone,
since I encountered this problem on entirely different mac configurations, different audio interfaces, OS version 10.11.6 El Capitan, it's time to consider it a major problem,

everything is fine until suddenly closing Nulloy shows a window popup "Nulloy quit unexpectedly" and after next launch there is no more sound coming out of nulloy,
I haven't found a fix for that yet, even changing audio interface doesn't help,
seems as if Nulloy output completely bricks itself and cannot be even reset back to re-initialize everything

**Comment by noscript** [comment]
Hi. Please try one​ of the 0.7 versions. Until next release I'm probably not going to tackle mac issues.

**Comment by tzzsmk** [comment]
thanks for heads up,

I tried the 0.7.5 version (replaced the 0.8.2), everything worked fine, but the skin was ugly,
so I tried 0.8 version (replaced the 0.7.5), and it throwed gstreamer error,
then I tried 0.8.2 version again (replaced the 0.8) and it works fine now,

leads me to conclusion something goes wrong with the .app folder itself, will examine further

**Comment by noscript** [comment]
I suppose this is not an issue anymore. Feel free to reopen otherwise.
