### ISSUE TITLE
Failes to run from directory with Cyrillic characters

### ISSUE THREAD

**Issue by sergeevabc** [nulloy/nulloy#142]
Windows 7 x64, Nulloy 0.8.2.pre43

1. Extract to some directory named in Russian, e.g. ```D:\Тест\Nulloy```
2. Launch ```Nulloy.exe``` and…

![](https://images.vfl.ru/ii/1520257459/2f411522/20836284.png)

Locking users in Latin directories in the age of Unicode is a shameful act. Please, fix.

**Comment by noscript** [comment]
Thanks for report. I will try to address it shortly.
