### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [nulloy/nulloy#144]
i've downloaded Version '0.8.2' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by noscript** [comment]
Thanks for pointing it out, will be fixed.

**Comment by core-code** [comment]
thanks!

**Comment by core-code** [comment]
not fixed in 0.9 release
<img width="259" alt="Screenshot 2022-02-24 at 12 24 24" src="https://user-images.githubusercontent.com/1261954/155515388-40a70597-b5c1-4c05-bd86-70603274a174.png">
:

**Comment by noscript** [comment]
Sorry about that. I will try to re-upload the release with the fix.

**Comment by core-code** [comment]
awesome, thanks!

**Comment by noscript** [comment]
Please try just uploaded 0.9.1, hopefully it's fixed now.

**Comment by core-code** [comment]
confirmed fixed, thanks so much
<img width="1341" alt="Screenshot 2022-02-25 at 16 35 12" src="https://user-images.githubusercontent.com/1261954/155743094-d5283524-b323-481d-9376-74cbdf4bd47b.png">
