### ISSUE TITLE
Nulloy takes AGES to launch.

### ISSUE THREAD

**Issue by lukeflegg** [nulloy/nulloy#153]
How is it Nulloy takes about 20x longer to open than VLC, Windows media player or anything else I use?
Having it as my default player is a real pain in the ass when I just want to quickly listen to a file.
It's not so bad opening subsequent files when Nulloy is already open.

**Comment by noscript** [comment]
How many files do you have in the playlist?

**Comment by SeanBannister** [comment]
I've also noted this problem under Windows 10 on two separate machines and one was a fresh machine with newly installed software. Even opening a fresh version of Nulloy with no playlist or file can take 15 seconds.

**Comment by noscript** [comment]
Could you please try the latest release? There have been many optimizations since the issue was open.

**Comment by SeanBannister** [comment]
Perfect thanks so much that seems to have solved it.

**Comment by noscript** [comment]
Happy to hear that!
