### ISSUE TITLE
Append to playlist

### ISSUE THREAD

**Issue by armandvedel** [nulloy/nulloy#155]
I have a feature request:

On mac, if I play a file when a playlist is already playing,  I get a new playlist with only the new file. I would like the option to play the new file immediately, but not clear the playlist. Instead it should add the song to the end of the playlist. Thanks!

**Comment by noscript** [comment]
In Preferences enable "Enqueue files". If you don't want start playing the file immediately, disable "Play enqueued file immediately".

![image](https://user-images.githubusercontent.com/717109/164091030-0194a733-c188-489c-a871-798729372e55.png)
