### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by fractalf** [nulloy/nulloy#160]
Please can you add support for Ubuntu 20.04 here?
https://nulloy.com/download/prerelease/

I tried to install the 19.10, but didn't work

```
-> % apt show nulloy  
Package: nulloy
Version: 0.8.2.pre63+22.1
Priority: extra
Section: sound
Maintainer: Sergey Vlasov <sergey@vlasov.me>
Installed-Size: 1 951 kB
Depends: libqtgui4, libqt4-script, libqt4-network, libgstreamer1.0-0, libtagc0
Suggests: trash-cli, gstreamer1.0-plugins-base, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly
Homepage: http://nulloy.com
Download-Size: 500 kB
APT-Sources: http://download.opensuse.org/repositories/multimedia:/apps:/nulloy:/prerelease/xUbuntu_19.10  Packages
Description: Music player with a waveform progress bar

-> % apt install nulloy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nulloy : Depends: libqtgui4 but it is not installable
          Depends: libqt4-script but it is not installable
          Depends: libqt4-network but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by noscript** [comment]
Since Ubuntu 20.04 Qt4 is no longer supported. I will try to finish my Qt5 port soon.

Until then you cat try adding an external repository with Qt4 https://askubuntu.com/questions/1234786/qt4-libqt4-in-ubuntu-20-04

**Comment by varlesh** [comment]
@fractalf i'm build qt5-version:
https://github.com/varlesh/focal-packages/raw/master/nulloy-qt5-0.8.2git20200611_amd64.deb

**Comment by Gontran-Macedoine** [comment]
I could install nulloy build qt-5 version but when launching nulloy I get this : 

`nulloy: /lib/x86_64-linux-gnu/libQt5Core.so.5: version Qt_5.15' not found (required by nulloy)`

And I can't find how to install Qt_5.15

Any idea how I could solve this ?

**Comment by noscript** [comment]
I created experimental repository with qt5 builds. These are even less tested than prerelease one.

https://download.opensuse.org/repositories/multimedia:/apps:/nulloy:/prerelease-qt5/

**Comment by varlesh** [comment]
@noscript remove depend from control `qtbase-abi-5-12-8` it's virtual package `libqt5core5a`
https://packages.ubuntu.com/focal/qtbase-abi-5-12-8
If Qt will be updated to 5.12-9 or more - it's not decide depends or for compatibility with other DEB-based distros. Neon, for example (use Qt 5.15.2 and not have `qtbase-abi-*` packages).

**Comment by noscript** [comment]
repository instructions have been updated, please check https://nulloy.com/download/prerelease/

**Comment by varlesh** [comment]
Guys, please remove `qtbase-abi` - it's virtual package `libqt5core5a` and problem for future updates

**Comment by fractalf** [comment]
Tried the latest pre-release build now and it worked fine. There are some icons missing, but I fixed that manually
