### ISSUE TITLE
One of dependency, qtscript, is deprecated

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#167]
According to https://wiki.qt.io/New_Features_in_Qt_5.5#Deprecated_Functionality

**Comment by noscript** [comment]
Yes I'm aware. It still supported through all Qt5 versions. But in Qt6 it may be no longer available.

QtScript is a major component of the player and replacing it would require a major rewrite. Unfortunately I don't have the capacity to do that anytime soon.
