### ISSUE TITLE
Add website repo to https://github.com/nulloy

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#170]

**Comment by noscript** [comment]
Now both GitHub logos link to repo
![image](https://user-images.githubusercontent.com/717109/120398012-0ab7af00-c342-11eb-9f44-ab5019bc642f.png)

**Comment by vitaly-zdanevich** [comment]
But this is links to Nulloy repo, not to website repo.

**Comment by noscript** [comment]
The website is not hosted on GitHub infrastructure and the source code is not public.

**Comment by vitaly-zdanevich** [comment]
Yes, but why?

**Comment by noscript** [comment]
The website is not a product and I see no reason to publish it. The source code is embracing, the commits history is a mess.
