### ISSUE TITLE
Is there a way to remove the window decorations (close and minimize) ?

### ISSUE THREAD

**Issue by ThomasTraineau** [nulloy/nulloy#172]
As I'm using a wm, that would look better ! (and being able to remove the top bar even more !)

**Comment by noscript** [comment]
You can achieve that using the Native skin.

**Comment by ThomasTraineau** [comment]
That works ! However is there a way to have a dark theme with it ?

**Comment by noscript** [comment]
You need to configure Qt5 to use a dark theme, you can even use themes from GTK. Please read about `QT_QPA_PLATFORMTHEME` environment variable.

**Comment by ThomasTraineau** [comment]
Do I have to recompile nulloy then ?

**Comment by noscript** [comment]
No need to recompile.

**Comment by ThomasTraineau** [comment]
Great, I managed to make it work !
