### ISSUE TITLE
Drag a file and copy to a finder window not working.

### ISSUE THREAD

**Issue by mariyanh** [nulloy/nulloy#174]
Hello,

After version Nulloy 0.8.2.pre112 the dragging out a track of Nulloy to a finder window is not working anymore.
This was a very good feature, for those using the player for pre-listening tracks and sorting.

It shows a forbidden sign now. Did you do this on purpose ? Can it be easily turned back on?

Cheers!

**Comment by noscript** [comment]
Nulloy 0.8.2.pre112 was the last pre-release still using Qt4, so I'm not surprised that migrating to Qt5 broke a few things.

I will try to bring this feature back.

**Comment by mariyanh** [comment]
Good point, and very good job! The player is much more stable now. Stopped quitting unexpectedly for me and I am using it again. Even loading tracks from a cloud loaded as a drive and works perfectly. Just waiting for the drag feature to work again and it will be N1! 

Cheers and Merry Christmas!

**Comment by noscript** [comment]
I have a fix for Nulloy but there is also a bug in Qt5 on macOS https://bugreports.qt.io/browse/QTBUG-99471 The bug prevents switching between copy and move actions, it is stuck in default move action.

Once there is a fix for Qt, I will test it and commit the fix for Nulloy.

**Comment by noscript** [comment]
Please try https://github.com/nulloy/nulloy/releases/tag/0.8.2.pre121
