### ISSUE TITLE
Volume changes onhover, please dont - I accidently touch it

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#178]

**Comment by noscript** [comment]
I cannot reproduce it, please give more details. Volume should change only on scroll wheel or click but not hover.

**Comment by vitaly-zdanevich** [comment]
In skin Slim - volume control at the right.

**Comment by noscript** [comment]
I mean what does actually happen when you hover it? Since what version?

**Comment by vitaly-zdanevich** [comment]
Recorded video https://www.youtube.com/watch?v=sjRiU7sKc1o

Firstly I noticed this in current 0.8.2 - build from `master`.

**Comment by noscript** [comment]
That's really odd. Does this happen with other skins, including the Native skin?

**Comment by vitaly-zdanevich** [comment]
Not with the default, but with Metro and Silver.

**Comment by noscript** [comment]
Is it also on Thinkpad with the red nipple?

**Comment by vitaly-zdanevich** [comment]
Yes, T430:

![image](https://user-images.githubusercontent.com/3514015/150426766-b0321761-7c01-43b0-b26b-069718df5695.png)

**Comment by noscript** [comment]
Does it happen if you scroll with the touchpad or mouse wheel instead?

**Comment by noscript** [comment]
Please check if 067bd20 also fixes this problem.

**Comment by vitaly-zdanevich** [comment]
Tested, this problem still exists.

**Comment by YudhaDev** [comment]
i have the same problem in version 0.9.5

**Comment by noscript** [comment]
@YudhaDev Do you also use Thinkpad?

@vitaly-zdanevich How do you move the pointer? Using mouse, touchpad or red nipple?

**Comment by YudhaDev** [comment]
> @YudhaDev Do you also use Thinkpad?
> 
> @vitaly-zdanevich How do you move the pointer? Using mouse, touchpad or red nipple?

sorry for the late reply, 
no, I'm using pc. I also notice that the issue only happens in certain themes/skin, such as metro, silver, and slim. yes except the native skin.
