### ISSUE TITLE
Lost track after Nulloy restart

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#182]
![nulloy-lost-track-after-player-restart](https://user-images.githubusercontent.com/3514015/149634510-be4bc2c9-f284-4a59-a7ac-9fb354c98d5b.gif)

**Comment by noscript** [comment]
Please post the portion of `nulloy.m3u` with the missing tracks. I winder if the paths somehow get corrupted.

**Comment by noscript** [comment]
I managed to reproduce it but those lost tracks are coming after expanding `.m3u` playlist. The playlists for some reason expand only after restart, I will fix it.

**Comment by vitaly-zdanevich** [comment]
I can not open m3u, getting `No such file or directory` for a first track.
