### ISSUE TITLE
Scrolling of playlist affect the volume

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#184]
I use ThinkPad laptop with the red nipple, and I experience more volume change when move nipple a little bit left/right.

https://user-images.githubusercontent.com/3514015/149985343-bb680f5a-c173-4195-979b-78959ce3c4fc.mp4

**Comment by noscript** [comment]
Please apply the patch and check if only `Qt::MouseEventNotSynthesized` is reported:
```diff
--- src/widgetCollection/volumeSlider.cpp
+++ src/widgetCollection/volumeSlider.cpp
@@ -49,11 +49,13 @@ void NVolumeSlider::mouseMoveEvent(QMouseEvent *event)
     showToolTip(event->x(), event->y());
 }
 
+#include <QDebug>
 void NVolumeSlider::wheelEvent(QWheelEvent *event)
 {
     NSlider::wheelEvent(event);
     event->accept();
     showToolTip(event->x(), event->y());
+    qDebug() << event->source();
 }
```

**Comment by vitaly-zdanevich** [comment]
Yes, this is reported:


https://user-images.githubusercontent.com/3514015/150426488-f3db10d8-b455-423b-b222-26fa6f7e5a92.mp4
