### ISSUE TITLE
Drag state persistent

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#185]
https://user-images.githubusercontent.com/3514015/150429902-70bf76fe-99ee-4c3a-a2c6-b26c4aef55ea.mp4

**Comment by noscript** [comment]
Hm, I cannot reproduce it. Does it happen with a file manager too?

**Comment by vitaly-zdanevich** [comment]
With system file manager works as expected.

**Comment by vitaly-zdanevich** [comment]
Cannot reproduce in 0.9.8.7
