### ISSUE TITLE
Error: GStreamer encountered a general stream error. MacOS Monterey

### ISSUE THREAD

**Issue by harmonymeow** [nulloy/nulloy#188]
![Screen Shot 2022-02-16 at 7 01 18 PM](https://user-images.githubusercontent.com/3032746/154396927-775b0949-1f87-42dd-b601-3260cee26619.png)
![Screen Shot 2022-02-16 at 7 03 26 PM](https://user-images.githubusercontent.com/3032746/154396947-78f11094-70c7-458d-a21c-895a57149afa.png)

**Comment by noscript** [comment]
Is the error with this particular file only?

**Comment by harmonymeow** [comment]
You are right. It only happens with the files I got from liveATC. Here is one of the files:
https://archive.liveatc.net/kpao/KPAO2-Twr-Feb-16-2022-2000Z.mp3

Note that these files play without issue in other players, such as QuickTime Player, VLC, and Audacity.

**Comment by noscript** [comment]
I have macOS Catalina and that file plays fine. What is the Nulloy version?

**Comment by harmonymeow** [comment]
0.8.2 Alpha
![Screen Shot 2022-02-17 at 4 49 48 PM](https://user-images.githubusercontent.com/3032746/154596428-00fe0ff8-628a-4c73-a823-9d552b9a3c1d.png)

Perhaps something to do with Monterey?

**Comment by noscript** [comment]
Please try pre-release build https://nulloy.com/download/prerelease/

**Comment by harmonymeow** [comment]
hey, you know what? I already did. yes, 121pre works.

**Comment by noscript** [comment]
Awesome :)
