### ISSUE TITLE
"Format is empty"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#189]
![image](https://user-images.githubusercontent.com/3514015/155633626-5d36f3e6-d9d6-44d0-8aa0-605edb836de5.png)

**Comment by noscript** [comment]
Please post the format string from the top-left section (Preferences -> Track Information).

**Comment by vitaly-zdanevich** [comment]
I did not change it.

`{%B kbps/|}{%s kHz|}`

**Comment by vitaly-zdanevich** [comment]
The version is 0.9

**Comment by vitaly-zdanevich** [comment]
Maybe this is a good time for 1.0 release, my Gentoo ebuild is almost finished.

**Comment by noscript** [comment]
I do not plan to bump the version to 1.0 any time soon.

**Comment by noscript** [comment]
Please try the master, a30c065 should fix this.
