### ISSUE TITLE
Metadata broken encoding ???????? ???????

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#194]
![image](https://user-images.githubusercontent.com/3514015/158497288-932e2750-ffac-46aa-bbd3-90750b326a49.png)

File: https://drive.google.com/file/d/1-ZmXJxaYG7gNKRkU_2osSQl88xEeJVmM

**Comment by vitaly-zdanevich** [comment]
Hm...

**Comment by vitaly-zdanevich** [comment]
Maybe try this file

![image](https://user-images.githubusercontent.com/3514015/158590362-12942b3e-6c02-4b54-8b97-17d966843688.png)

https://meanna.ru/bitrix/templates/meanna_1.0_audio/audio/compilation/stakan_s_voobrazheniem_(feat_da_krai).mp3

**Comment by vitaly-zdanevich** [comment]
But this defect is not always

![image](https://user-images.githubusercontent.com/3514015/158590573-a24be202-a3a5-4027-bf27-7ff1cdf6f51a.png)

Correct audio https://meanna.ru/bitrix/templates/meanna_1.0_audio/audio/compilation/parallel_mir.mp3

**Comment by vitaly-zdanevich** [comment]
Still broken encoding

![image](https://user-images.githubusercontent.com/3514015/158706369-3b5b43a8-6258-46d9-9560-159e5b855412.png)

**Comment by noscript** [comment]
Yes, there was still a bug.

You have to select "windows-1251" encoding in Preferences to render the tags properly for that file. However I recommend to convert the tags to UTF-8.

**Comment by vitaly-zdanevich** [comment]
Maybe you should detect encoding for every file.

**Comment by noscript** [comment]
> Maybe you should detect encoding for every file.

That is impossible. Web browsers never succeeded in this either.
