### ISSUE TITLE
Periodic crashes when play short audio files

### ISSUE THREAD

**Issue by SeanBannister** [nulloy/nulloy#198]
When playing short audio files such as audio samples around 1 second long Nulloy sometimes crashes on open. I've had this happen for a few years now under Windows 10.

It seems to work fine if you drag them into a playlist but simply double clicking short audio files which are associated with Nulloy as the player in windows tends to crash it.

**Comment by noscript** [comment]
Gapless playback for short files indeed was dead locks. For very short files GStreamer tries to preload multiple files at once, and handing it in the playlist properly is too much work.

As a workaround I disabled gapless playback for files under 1 second. Expect the fix in the next release.

**Comment by noscript** [comment]
Please try 0.9.7 release.

**Comment by SeanBannister** [comment]
Working great on my end, thanks for your work on this.
