### ISSUE TITLE
Drop `-s` strip flag during compilation?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#200]
Hi, I got this bug report https://bugs.gentoo.org/856292

What do you think about it?

**Comment by noscript** [comment]
Why is unstipped version needed?

Stripping doesn't happen when configuring with `--debug`.

**Comment by noscript** [comment]
Additional qmake options can be set in `.qmake.cache` after running the configure script. So to disable stripping:
```sh
echo "CONFIG += nostrip" >> .qmake.cache
```

**Comment by vitaly-zdanevich** [comment]
On [Gentoo bug link](https://doc.qt.io/qt-5/qmake-variable-reference.html#installs) I see the link to documentation with:
```
INSTALLS has a .CONFIG member that can take several values:

nostrip | If set, the typical Unix strip functionality is turned off and the debug information will remain in the binary.
```
What do you think about it? No other ways to set it?

**Comment by noscript** [comment]
Is appending `nostrip` to `.qmake.cache` not enough?

**Comment by vitaly-zdanevich** [comment]
[Patching of nulloy.pro](https://github.com/gentoo/guru/commit/ceafffcacd1fe1fe14c1e4b1ad52662f97a96eaf) does not work?

**Comment by vitaly-zdanevich** [comment]
Fixed here https://github.com/gentoo/guru/commit/fde97c7e5637424e146fba67974862ca33ad6f87
