### ISSUE TITLE
Malformed Unicode tags when an encoding is selected

### ISSUE THREAD

**Issue by Carmina16** [nulloy/nulloy#213]
If some single-byte encoding is selected in Preferences, Unicode tag values are shown incorrectly in the UI: as if their unicode values were truncated to a single byte. Unicode text should not depend on a legacy tag encoding.

**Comment by Carmina16** [comment]
Of course it is possible. Unicode tags have the string type byte that indicates the encoding.

**Comment by noscript** [comment]
Ok, I will see what can be done.
