### ISSUE TITLE
Next file in playlist doesn't play automatically (bug)

### ISSUE THREAD

**Issue by chumariesco** [nulloy/nulloy#220]
The playhead stops scrolling the waveform a little before an audio file ends. Then the playlist jumps to the next file: the playhead doesn't scroll while the end of the previous file sounds. Then the current file now in the playlist starts sounding and scrolling for one or two seconds and the sound stops, but the playhead keeps on scrolling–with no sound at all.
If files are individually played in the playlist they sound, but when let alone to play one after the other within the playlist the previous behavior will repeat, each time jumping to the next file there won't be any sound after one or two seconds.

Any idea why is this? I tried updating all gst-plugins but still no difference. Running version 0.9.5 on Arch Linux KDE latest versions.

**Comment by noscript** [comment]
Yes, I can reproduce it on `master` but not on 0.9.5. I guess the version on Arch is built from master also?

**Comment by noscript** [comment]
I reported [bug](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1798) to GStreamer. In meanwhile I will have to disable the pitch control feature.

**Comment by chumariesco** [comment]
That‘s amazing! That you put hand-on :)
The arch package is git based, do you know if that means that the temporary fix (pitch disable) will be reflected there immediately?

https://aur.archlinux.org/packages/nulloy-git

**Comment by noscript** [comment]
>do you know if that means that the temporary fix (pitch disable) will be reflected there immediately?

Yes, if the package is updated to latest master. Maybe the maintainer needs to trigger a recheck.

**Comment by chumariesco** [comment]
Amazing! AUR package updated to 0.9.8.0 works perfectly. Nulloy is a hidden jewel, thanks Sergey.

**Comment by noscript** [comment]
Thank you too!
