### ISSUE TITLE
Can't install on Debian Bookworm - wants qtbase-abi-5-15-2 but 5-15-8 is installed.

### ISSUE THREAD

**Issue by kr37** [nulloy/nulloy#222]
When I upgraded to Debian bookworm, I can no longer install Nulloy properly. I'm so sad. I love Nulloy!

Actually, by editing 
`/var/lib/apt/lists/download.opensuse.org_repositories_multimedia:_apps:_nulloy_bullseye_Packages` 
to refer to `qtbase-abi-5-15-8` instead of -5-15-2, then it does install (with a dpkg error) and seems to function fine. 

But this leaves my dpkg/apt messed up so that I can't upgrade anything else. So this isn't really a solution.  The package seems to need to refer to 5-15-8.

**Comment by noscript** [comment]
`bookworm` repository has been updated, please try again.
