### ISSUE TITLE
My beautiful custom theme is broken: currently playing item is black on black :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#231]
![image](https://github.com/nulloy/nulloy/assets/3514015/01cb3713-9d8a-48dd-bbce-90d24aa62bb2)

I do not understand, what should I fix now?

The theme repo https://gitlab.com/vitaly-zdanevich/nulloy-theme-night/-/blob/main/form.ui

**Comment by noscript** [comment]
Please change `qproperty-current_text_color` to `qproperty-playing_text_color`. `current` term in QListWidget is reserved for selected item, so I had to rename it.

**Comment by vitaly-zdanevich** [comment]
Thanks, I will try this when will be at home.

Still do not want to include this theme?

**Comment by noscript** [comment]
I'm sorry. The fewer skins I need to maintain, the more time I have for other things. If I decide to include a skin, it has to be something unique.

I added it to the wiki page https://github.com/nulloy/nulloy/wiki/3rd-Party-Skins and later I will put link to the wiki on the main website.

P.S. I'm in the middle of rewriting Nulloy in QML, it means this skin will need to be redone. However QML makes things much easier in that regard.

**Comment by vitaly-zdanevich** [comment]
Thanks, solved at https://gitlab.com/vitaly-zdanevich/nulloy-theme-night/-/commit/6147ca6a58f874940ad7acae4106b7f28158fe92
