### ISSUE TITLE
ppa update issue

### ISSUE THREAD

**Issue by rcspam** [nulloy/nulloy#58]
Hi Sergey,
Your ppa is down, do you know that ?

**Comment by noscript** [comment]
Hi. I have moved the PPA to ppa:nulloy/testing. I announced that in Twitter and Facebook group a couple days ago :)

**Comment by rcspam** [comment]
Sorry i dont follow twitter or facebook (i am a wild man ;) I speak about your last change last: ppa:nulloy/testing 
http://ppa.launchpad.net/nulloy/testing/ubuntu is "404 not found"

**Comment by noscript** [comment]
That's weird, your url works for me. For example, the full url to packages:
http://ppa.launchpad.net/nulloy/testing/ubuntu/pool/main/n/nulloy/

PPA web page:
https://launchpad.net/~nulloy/+archive/ubuntu/testing

**Comment by rcspam** [comment]
The PPA web page is ok for me too but "404 not found" for http://ppa.launchpad.net/nulloy/testing/ubuntu/pool/main/n/nulloy/

![screenshot1](https://cloud.githubusercontent.com/assets/10021906/7555141/bc2edd94-f742-11e4-90e3-4654feab3bf2.png)

**Comment by noscript** [comment]
Hm, why does it say port 443? Shouldn't it be 80? This is what I see:

![nulloy-testing](https://cloud.githubusercontent.com/assets/717109/7555175/e02ed204-f74b-11e4-852b-c77cfaea1eaf.png)

What if you try with the IP? http://91.189.95.83:80/nulloy/testing/ubuntu/pool/main/n/nulloy/

**Comment by rcspam** [comment]
Are you do something it's ok since one minute ago ?!

Anyway, Thank you for your work...
Best Regards

**Comment by noscript** [comment]
No, haven't touched anything.

**Comment by rcspam** [comment]
In fact, it was an "http anywhere extention" problem, sorry !!

**Comment by noscript** [comment]
No problem :)
