### ISSUE TITLE
PluginGStreamer failed to load

### ISSUE THREAD

**Issue by giankam** [nulloy/nulloy#61]
Hi,
I've a problem with Nulloy. Every time a try to run I get the error box windows "Failed to load the plugin: ......PluginGStreamer.dll"

What can I do to fix it?
Thanks

**Comment by noscript** [comment]
You are not the first who reports this problem, so far I haven't found what causes it as I never could reproduce myself. I guess GStreamer fails to find and/or load the plugins.

Are using English version of Windows?

I'm preparing the next 0.8 release with GStreamer 1.0, which supports dumbing a log file. That will allow me to investigate the problem fully.

For now, please try clear both Qt and GStremaer plugins cache and run Nulloy again:
* Remove `C:\Users\<your user name>\.gstreamer-0.10` directory.
* Open `regedit` and browse to `HKEY_CURRENT_USER\Software\Trolltech\OrganizationDefaults`. Remove all the keys that start with `Qt Plugin Cache`. For example: `Qt Plugin Cache 4.8.false`, `Qt Plugin Cache 4.8.debug` and others.

**Comment by noscript** [comment]
Please try the new 0.8 version. Hopefully it will work for you just fine. Feel free to reopen the issue if there is still a problem.

**Comment by giankam** [comment]
Hi,

it works great now many thanks.

A question, is there a way to select just a part of a song and loop it?

Thanks again
Giancarlo

**Comment by noscript** [comment]
There is no at the moment, but feel free to create a feature request.

**Comment by noscript** [comment]
> is there a way to select just a part of a song and loop it?

Created a separate issue #86
