### ISSUE TITLE
Add pitch control

### ISSUE THREAD

**Issue by noscript** [nulloy/nulloy#62]
Requested via twitter.

**Comment by radinsky** [comment]
could be very nice, waiting for this one

**Comment by neverlink** [comment]
Please add this, it's the only thing missing for me on this player.
MPC-HC does this, ctrl+up/down arrow changes the speed (and pitch)

**Comment by noscript** [comment]
Please list some use cases where pitch control can be useful.

**Comment by radinsky** [comment]
Listen to the track on different tempo..

**Comment by noscript** [comment]
Pitch control is now also implemented.

**Comment by neverlink** [comment]
WE LOVE YOU!
