### ISSUE TITLE
Doesn't sounds with WIN8 64Bits

### ISSUE THREAD

**Issue by deejal10** [nulloy/nulloy#63]
With Nulloy 0.75 32 bits version works perfectly!

Thanks, the best player ever!!!

**Comment by noscript** [comment]
Sorry about that. I have re-uploaded the build with sound fixed.

**Comment by deejal10** [comment]
Oh god!! Lot's of thanks!!! Really great job!!!

Maybe a pitch control in the next upgrade? :P
El dia 09/07/2015 12.24, "Sergey Vlasov" <notifications@github.com> va
escriure:
