### ISSUE TITLE
Not displaying track info in version 0.8

### ISSUE THREAD

**Issue by vacuidad** [nulloy/nulloy#66]
Hi, I'm huge fan of your audio player. It's just great !

I was using the 0.7 and have no problems.

Now I update to 0.8 and for some reason I can't see the track info. I also cannot change the info to be display, I mean, I can write the new info codes, but it doesn't appear on the program, even after restarting it. Also it isn't displaying the mouse position, nor the track duration, etc... just nothing.

The file is a standard 16 bit stereo wav.

I notice that this versions loads the waveform fas
![nulloy](https://cloud.githubusercontent.com/assets/13421150/8781216/1f04374c-2ee4-11e5-8bbc-840bc295d333.jpg)

ter, so I want to keep it !

Any idea?

I'm using windows 8.1 x64 bits in english, core i7, 16 gb ram, here is a printed screen...

Thank you so much for this software !!

**Comment by noscript** [comment]
Does it show anything on the Slim skin?

**Comment by noscript** [comment]
Please try the latest 0.8.1 release.

**Comment by Egor-Muratov** [comment]
I have similar problem, too. If path to the file include russian(cirillic) symols, then Nulloy doesn't show "information about track"
0.7.5 work perfect with all skin.
0.8+ doesn't show with all skin.
W10 32bit - Russian.

**Comment by noscript** [comment]
>I have similar problem, too. If path to the file include russian(cirillic) symbols, then Nulloy doesn't show "information about track"

If the tags are not stored in Utf-8, you would need to manually select the encoding in Preferences.

There have been some fixes regarding the track info. Please try the latest 0.9.1 release.
Feel free to reopen or report a new issue.
