### ISSUE TITLE
Large waveform view?

### ISSUE THREAD

**Issue by dzg** [nulloy/nulloy#71]
In the last version I was able to display a large waveform of audio file.

Now I only see a small waveform and playlist.

Is there any way to get the old view back? I'd rather not see playlist at all.

Thanks

**Comment by noscript** [comment]
You can resize the waveform, pull the grip below:
![](http://nulloy.com/files/news/waveform-height.png)

Also, you can switch the skin in Preferences. Right click on the window or <kbd>Ctrl</kbd>+<kbd>P</kbd>.

**Comment by dzg** [comment]
AHA! Great!
