### ISSUE TITLE
Error on Mac Os X 10.9.5

### ISSUE THREAD

**Issue by svetlinstaikov** [nulloy/nulloy#77]
Here is the error
"/Users/staikov/Desktop/Elvis Presley - Got My Mojo Working.wav
Error: ÐÐ¸Ð¿ÑÐ²Ð° ÐµÐ»ÐµÐ¼ÐµÐ½ÑÑÑ âautoaudiosinkâ.

/Users/staikov/Desktop
Error: Internal data flow error."
On my other Macbook Pro with the same OS it is working fine

**Comment by noscript** [comment]
Here is a version with the fix https://github.com/nulloy/nulloy/releases/download/0.8-autosink-fix/Nulloy-0.8-autosink-fix-universal.dmg

I will try to make an official release this week.

**Comment by svetlinstaikov** [comment]
Thank you! I tried the new build. The diffrence is only that the error string is properly translated:
"/Users/staikov/Desktop/Elvis Presley - Got My Mojo Working_synced.wav
Error: Internal data flow error.

/Users/staikov/Desktop
Error: Вътрешна грешка на потока от данни."

**Comment by noscript** [comment]
What is your sound card model?

**Comment by svetlinstaikov** [comment]
I have diffrerent sound cards with one and the same machine - AVID Mbox 2 Pro and Steinberg MR816X

**Comment by svetlinstaikov** [comment]
The error is with both

**Comment by noscript** [comment]
What about playing other formats? mp3, flac?

**Comment by svetlinstaikov** [comment]
Wav and mp3. Never tried FLAC

**Comment by noscript** [comment]
So even mp3 produces the same error? Very strange. Please try some mp3 in the original 0.8 version.

**Comment by svetlinstaikov** [comment]
This is with the original version:
"/Volumes/Mac/Users/staikov/Guitar/capriccio 24.mp3
Error: GStreamer Ð¿Ð¾Ð»ÑÑÐ¸ Ð¾Ð±ÑÐ° Ð³ÑÐµÑÐºÐ° Ð² Ð¿Ð¾ÑÐ¾ÐºÐ° Ð¾Ñ Ð´Ð°Ð½Ð½Ð¸.

/Users/staikov/Desktop
Error: ÐÑÑÑÐµÑÐ½Ð° Ð³ÑÐµÑÐºÐ° Ð½Ð° Ð¿Ð¾ÑÐ¾ÐºÐ° Ð¾Ñ Ð´Ð°Ð½Ð½Ð¸."

**Comment by noscript** [comment]
Thanks. Now it makes more sense.

0.8-autosink-fix release fixes the error with wav files but there is another problem.

GStreamer1.0 has [issues](https://github.com/clementine-player/Clementine/issues/4764) with external sound cards on Mac. I'm quite sure you will get the same error with Clementine that also uses GStreamer1.0. You can try with the latest build http://builds.clementine-player.org/mac/

Basically this needs to be reported to GStreamer developers if hasn't been done already. But I don't have a real Mac and cannot provide the developers with any additional information. I will try to connect my Focusrite to virtual machine and see if I can reproduce it.

Until then you can use version 0.7.5 https://github.com/nulloy/nulloy/releases/download/0.7.5/Nulloy-0.7.5.dmg that uses GStreamer0.10 and doesn't have this problem.

**Comment by svetlinstaikov** [comment]
0.7.5 is working fine, thank you!

**Comment by noscript** [comment]
The issue with external card will be handled separately in #85.
