### ISSUE TITLE
Added to homebrew-cask

### ISSUE THREAD

**Issue by diimdeep** [nulloy/nulloy#78]
Will be possible to install in OSX with `brew cask install nulloy`
https://github.com/caskroom/homebrew-cask/pull/14134

**Comment by noscript** [comment]
So cool, thank you! Would you like me to bump you with new version notifications?

**Comment by diimdeep** [comment]
Yeah, np)

**Comment by noscript** [comment]
0.8.1 is released now. Keep in mind the build is not universal anymore. Thanks!
