### ISSUE TITLE
Add playback speed control

### ISSUE THREAD

**Issue by noscript** [nulloy/nulloy#80]

**Comment by crackajack77** [comment]
omg yes please

**Comment by hpbaxx** [comment]
is this feature coming soon?

**Comment by noscript** [comment]
I hope so.

**Comment by kr37** [comment]
Right now, I go back and forth between VLC and Nulloy. The waveform in Nulloy lets me find the right spot in the file, but then when typing notes, I need to be able to slow down the playback, so I need VLC.  I'd love if Nulloy could offer this same feature. It's really great being able to slow down with a keyboard shortcut - [  and speed up with ].   Still it's a nice player as is.

**Comment by vitaly-zdanevich** [comment]
Yep, I think many users of Nulloy use it for some lectures.

**Comment by kr37** [comment]
Sorry if I'm being ignorant. It seems that you've done this already, but I don't know how to use it?

**Comment by noscript** [comment]
The feature will be available in the next release, which I hope to make after addressing some of the bug reports.

It is possible to build the player from source.
