### ISSUE TITLE
mouse hover time

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#87]
![mouse](https://cloud.githubusercontent.com/assets/3514015/11906053/fc02d3ac-a5da-11e5-8f7f-e328ae6b3b4d.png)

maybe because I have big cursor - size 48 of something (maybe px) in preferences
Xubuntu 14.04.3

**Comment by noscript** [comment]
It looks to be Xfce issue. According to [QToolTip::showText()](http://doc.qt.io/qt-4.8/qtooltip.html#showText):

> The tool tip will be shown with a platform specific offset from this point of interest.

Try to reproduce with any other Qt4 app: Vrtualbox, qBittorrent, VLC.

**Comment by vitaly-zdanevich** [comment]
![vlc](https://cloud.githubusercontent.com/assets/3514015/11908865/3ac33620-a5f1-11e5-9d0d-379cdfdc00e1.png)

Hmm... VLC have another type of hover... Or you mean something else reproducing?

**Comment by noscript** [comment]
That's a custom VLC tooltip. Try to hover playback button instead.

**Comment by vitaly-zdanevich** [comment]
![vlc](https://cloud.githubusercontent.com/assets/3514015/11909299/c701e362-a5f5-11e5-8c50-81f31f7075bb.png)

And you can't fix this?

**Comment by noscript** [comment]
Unfortunately trying to fix it in Nulloy is unfeasible. This should be forwarded to either Xfce or Qt developers instead.

But if you are able to build Nulloy from source you can put an offset for waveform tooltip:

```diff
--- src/trackInfoWidget.cpp
+++ src/trackInfoWidget.cpp
@@ -235,6 +235,6 @@ void NTrackInfoWidget::showToolTip(int x, int y)
     }
 
     text = tagReader->toString(text);
-    QToolTip::showText(mapToGlobal(QPoint(x, y)), text);
+    QToolTip::showText(mapToGlobal(QPoint(x, y) + QPoint(30, 30)), text);
 }
```

**Comment by vitaly-zdanevich** [comment]
ok, I understand - problem with framework that you use. But maybe you can add few lines to the code of Nulloy and add checkbox to the `Preferences` with text something like `Move tooltip to 30px`? I think this is not hard but useful.

**Comment by noscript** [comment]
I will see what can be done.

**Comment by noscript** [comment]
The setting can now be found in Preferences.
