### ISSUE TITLE
open file not working

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#88]
I tried `Ctrl + O`, select my `ogg` file, push `Enter` - file selector window has been closed but nothing happend.

Nulloy 0.8.1
Xubuntu 14.04.3 i386

**Comment by noscript** [comment]
I think the file filters list is missing `*.ogg`. You can append it in Preferences, although it should be there already by default.

**Comment by vitaly-zdanevich** [comment]
Works as expected now.
