### ISSUE TITLE
Add a new track restart the current track

### ISSUE THREAD

**Issue by Thorkul** [nulloy/nulloy#95]
Hello,
Add a new track restart the current track. It's little uncomfortable ...
Nulloy 0.8.2-testing-1~538~ubuntu14.04.1 Alpha

**Comment by noscript** [comment]
How do you add the new track exactly? If you drag it to the playlist - nothing should restart.

**Comment by Thorkul** [comment]
For add a new track to current playlist, I double click the track in the directory.

**Comment by noscript** [comment]
Uncheck in Preferences: "Play enqueued files immediately"

**Comment by Thorkul** [comment]
Already uncheck.
You want that I explain more my problem ? Sorry for mi bad english.

**Comment by noscript** [comment]
Sorry, that's a bug. I can reproduce it.
