### ISSUE TITLE
Keyboard media buttons y function button

### ISSUE THREAD

**Issue by Thorkul** [nulloy/nulloy#99]
![acer-m3-581tg-rys2-full2](https://cloud.githubusercontent.com/assets/1025754/12829682/ac2c63a8-cb8b-11e5-8c9d-9e0425ae7a94.jpg)

Not work :'(

**Comment by noscript** [comment]
Works for me.

What happens if you try to assign a shortcut with these keys? Are they recognized?

**Comment by Thorkul** [comment]
In fact, there are various key who not work (only in Nulloy) like shortcut.
![acer-m3-581tg-rys2-full2](https://cloud.githubusercontent.com/assets/1025754/12830671/cca08a74-cb90-11e5-840e-73d77c384afa.jpg)

**Comment by noscript** [comment]
Your desktop environment or another application could be consuming them. Try to set shortcuts in some other media application like VLC and see if it works.

**Comment by Thorkul** [comment]
En fact, in VLC no work, but en Rhythmbox work.
It would seem to me, it's Gnome Shell with gnome-settings-daemon who pass shortcuts on applications.
This can explain that only some applications work with this shortcuts.
![capture du 2016-02-04 23 12 52](https://cloud.githubusercontent.com/assets/1025754/12831813/9bc8ac00-cb96-11e5-937b-1987d5f3643b.png)

**Comment by noscript** [comment]
Rhythmbox is the core Gnome music player AFAIK. Unbinding they keys from Gnome should make them work elsewhere.

**Comment by Thorkul** [comment]
Hello !

I have solutions :
- assign commands (nulloy --pause, nulloy --stop ...) to shortcuts in gnome control panel

OR

- delete the pre-assigned commands with media keys in gnome control center. When media keys no are assigned, they are detected in Nulloy.

**Comment by noscript** [comment]
Way to go :+1:
